In [17]:
import pandas as pd

d1 = pd.read_csv(r"C:\Users\20245179\OneDrive - TU Eindhoven\Research Paper\Data\final_data.csv")
d2 = pd.read_csv(r"C:\Users\20245179\OneDrive - TU Eindhoven\Research Paper\Data\data_23.csv")

In [18]:
d1

,parent_id,id,author_id,time,title,text,post_url,reactions,year,nu_words,ha_id,text_ha
0,ZmVlZGJhY2s6MjA0MDM2MDg0NjAxMzE1NA==,ZmVlZGJhY2s6MjA0MDM2MDg0NjAxMzE1NF8yMDQxMDI4Nj...,100001659249038,2019-04-02T22:14:59,NaN,hoeveel KWh hebben de zonnepanelen op de wezen...,0,0,2019,10,100034431854919,De zonnepanelen op het dak van ons kantoor doe...
1,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzMw==,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzM18yMDc5MTcxNj...,1204819098,2018-12-21T15:37:26,NaN,Dan kom ik langs voor sleutels en krijg er gra...,0,0,2018,17,100031130900343,IN ACTI-UM | Onze vakmannen vervangen bij iede...
2,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzMw==,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzM18yMDc4ODYzNj...,627271250,2018-12-21T10:57:48,NaN,"Mmmm, iets nieuws? Wij hebben in maart geen wi...",0,0,2018,10,100031130900343,IN ACTI-UM | Onze vakmannen vervangen bij iede...
3,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNA==,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNF8yMDc1OTI1Mj...,100001478616616,2018-08-01T15:22:31,NaN,Het zou beter zijn als Samenwerking een aantal...,0,0,2018,23,100067754302074,Een hoog energieverbruik is slecht voor het mi...
4,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNA==,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNF8yMDczOTE5Nj...,100000855817347,2018-07-31T11:51:36,NaN,Leuk als je in een woning woont met warmtepomp...,0,0,2018,34,100067754302074,Een hoog energieverbruik is slecht voor het mi...
...,...,...,...,...,...,...,...,...,...,...,...,...
3192,ZmVlZGJhY2s6OTU1MjE0NDg0ODMyNDYw,ZmVlZGJhY2s6OTU1MjE0NDg0ODMyNDYwXzk1NTIyMDUzND...,100001182464975,2019-07-30T10:57:55,NaN,Kijk onze wijk Herma Van Es Sergio Antonio Pau...,0,2,2019,20,100063528101921,Vorige week zijn de laatste huizen van 't Getf...
3193,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2NjA4NTQ4Nz...,596212634,2020-10-22T12:40:07,NaN,Is er genoeg ventilatie en / of kunnen ramen g...,0,0,2020,10,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...
3194,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2NTQwMTMyNz...,100001224379149,2020-10-21T15:54:40,NaN,Sylvana Visser kan je dus straks gebruik van m...,0,0,2020,21,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...
3195,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2MzU0MDgwNz...,100002916564091,2020-10-19T10:14:18,NaN,Komen er nog meer werkplekken bij? Of blijft h...,0,0,2020,16,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...
3196,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2MzUzNzE4ND...,1307930730,2020-10-19T10:06:29,NaN,Goed initiatief.,0,1,2020,2,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...

In [19]:

print(d1.columns)
print(d2.columns)

Index(['parent_id', 'id', 'author_id', 'time', 'title', 'text', 'post_url',
       'reactions', 'year', 'nu_words', 'ha_id', 'text_ha'],
      dtype='object')
Index(['Unnamed: 0', 'id', 'author_id', 'author_name', 'time', 'title', 'text',
       'post_url', 'reactions', 'shared', 'n_comments',
       'n_comments_restrict_company', 'n_comments_distinct_authors',
       'n_comments_without_text', 'year', 'month', 'sentiment', 'weekday',
       'energy', 'zon', 'renovatie', 'duurzaam', 'duurz_en_zon', 'huur',
       'has_comments', 'has_comments_distinct_authors', 'has_reactions',
       'has_shared', 'nu_words', 'picture', 'tweet', 'abstract', 'long'],
      dtype='object')

In [21]:
d2

,Unnamed: 0,id,author_id,author_name,time,title,text,post_url,reactions,shared,...,huur,has_comments,has_comments_distinct_authors,has_reactions,has_shared,nu_words,picture,tweet,abstract,long
0,42,ZmVlZGJhY2s6MTEzMDA2MDc4MTIzMTM0Nw==,100026823082884,Jutphaas Wonen,2023-03-30 08:47:35,NaN,Wil je het klimaat een handje helpen maar zie ...,https://www.facebook.com/Jutphaaswonen/posts/p...,0,0,...,0,0,0,0,0,67,0,0,1,0
1,344,ZmVlZGJhY2s6ODc2MzYwMjQwMDA3MzY5,100029002046246,De Huismeesters,2023-01-21 10:06:06,NaN,'Welke apparaten slurpen de meeste stroom?' En...,https://www.facebook.com/dehuismeesters/posts/...,2,0,...,0,0,0,1,0,100,0,0,1,0
2,346,ZmVlZGJhY2s6ODcwOTM3MDIzODgzMDI0,100029002046246,De Huismeesters,2023-01-13 19:00:03,NaN,"Man, man, man, wat zijn we hier trots op! De w...",https://www.facebook.com/dehuismeesters/posts/...,20,3,...,0,0,0,1,1,56,0,0,1,0
3,354,ZmVlZGJhY2s6ODkwNjYwNDQxOTEwNjgy,100029002046246,De Huismeesters,2023-02-09 14:18:56,NaN,Een energieke hoofdrol voor onze Esther in het...,https://www.facebook.com/dehuismeesters/posts/...,10,0,...,0,0,0,1,0,45,0,0,1,0
4,355,ZmVlZGJhY2s6ODkwODQyODE1MjI1Nzc4,100029002046246,De Huismeesters,2023-02-09 18:57:03,NaN,"Vertel het aan je buren, deel het in de buurta...",https://www.facebook.com/dehuismeesters/posts/...,9,4,...,0,0,0,1,1,51,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,47522,ZmVlZGJhY2s6MTgxOTAzNzgxMjE2MzM4,100081901518277,Hef Wonen,2023-02-14 09:53:57,NaN,Vandaag is het Valentijnsdag De dag om iemand ...,https://www.facebook.com/HefWonen/posts/pfbid0...,2,0,...,0,1,1,1,0,22,0,1,0,0
2841,47523,ZmVlZGJhY2s6MTgzNzg3MTc3Njk0NjY1,100081901518277,Hef Wonen,2023-02-22 14:24:49,NaN,Kun je de huur niet of niet op tijd betalen? N...,https://www.facebook.com/HefWonen/posts/pfbid0...,3,0,...,1,0,0,1,0,39,0,0,1,0
2842,47524,ZmVlZGJhY2s6MTk0MTcxNjQzMzIyODg1,100081901518277,Hef Wonen,2023-03-14 12:04:03,NaN,De wooncrisis voelen we in heel Nederland. Dit...,https://www.facebook.com/HefWonen/posts/pfbid0...,1,0,...,0,0,0,1,0,33,0,0,1,0
2843,47525,ZmVlZGJhY2s6MTk5NjQ1NDE2MTA4ODQx,100081901518277,Hef Wonen,2023-03-23 15:34:49,NaN,Vandaag start de Ramadan! Hiermee begint een v...,https://www.facebook.com/HefWonen/posts/pfbid0...,7,0,...,0,0,0,1,0,23,0,1,0,0
2844,47526,ZmVlZGJhY2s6MTkwMDM5MjYzNzM2MTIz,100081901518277,Hef Wonen,2023-03-07 09:48:11,NaN,Met Koningsdag kleurt Rotterdam oranje. Het wo...,https://www.facebook.com/HefWonen/posts/pfbid0...,7,1,...,0,0,0,1,1,71,0,0,1,0

In [14]:
# Ensure keys are the same type
d1['ha_id'] = d1['ha_id'].astype(str)
d2['author_id'] = d2['author_id'].astype(str)

# Create lookup dictionaries from d2 for all columns we want to add
author_map = dict(zip(d2['author_id'], d2['author_name']))
time_map = dict(zip(d2['author_id'], d2['time']))
weekday_map = dict(zip(d2['author_id'], d2['weekday']))
month_map = dict(zip(d2['author_id'], d2['month']))
year_map = dict(zip(d2['author_id'], d2['year']))

# Map all columns to d1
d1['author_name'] = d1['ha_id'].map(author_map)
d1['time'] = d1['ha_id'].map(time_map)
d1['weekday'] = d1['ha_id'].map(weekday_map)
d1['month'] = d1['ha_id'].map(month_map)
d1['year'] = d1['ha_id'].map(year_map)

In [15]:
d1

,parent_id,id,author_id,time,title,text,post_url,reactions,year,nu_words,ha_id,text_ha,author_name,weekday,month
0,ZmVlZGJhY2s6MjA0MDM2MDg0NjAxMzE1NA==,ZmVlZGJhY2s6MjA0MDM2MDg0NjAxMzE1NF8yMDQxMDI4Nj...,100001659249038,2023-04-26 12:11:57,NaN,hoeveel KWh hebben de zonnepanelen op de wezen...,0,0,2023.0,10,100034431854919,De zonnepanelen op het dak van ons kantoor doe...,WormerWonen,Wednesday,4.0
1,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzMw==,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzM18yMDc5MTcxNj...,1204819098,2023-04-17 20:00:44,NaN,Dan kom ik langs voor sleutels en krijg er gra...,0,0,2023.0,17,100031130900343,IN ACTI-UM | Onze vakmannen vervangen bij iede...,Actium,Monday,4.0
2,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzMw==,ZmVlZGJhY2s6MjA0ODM5MDA5ODU1MTgzM18yMDc4ODYzNj...,627271250,2023-04-17 20:00:44,NaN,"Mmmm, iets nieuws? Wij hebben in maart geen wi...",0,0,2023.0,10,100031130900343,IN ACTI-UM | Onze vakmannen vervangen bij iede...,Actium,Monday,4.0
3,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNA==,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNF8yMDc1OTI1Mj...,100001478616616,NaN,NaN,Het zou beter zijn als Samenwerking een aantal...,0,0,NaN,23,100067754302074,Een hoog energieverbruik is slecht voor het mi...,NaN,NaN,NaN
4,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNA==,ZmVlZGJhY2s6MjA1MDEwNjkzMTY4ODQzNF8yMDczOTE5Nj...,100000855817347,NaN,NaN,Leuk als je in een woning woont met warmtepomp...,0,0,NaN,34,100067754302074,Een hoog energieverbruik is slecht voor het mi...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,ZmVlZGJhY2s6OTU1MjE0NDg0ODMyNDYw,ZmVlZGJhY2s6OTU1MjE0NDg0ODMyNDYwXzk1NTIyMDUzND...,100001182464975,2023-04-06 14:31:11,NaN,Kijk onze wijk Herma Van Es Sergio Antonio Pau...,0,2,2023.0,20,100063528101921,Vorige week zijn de laatste huizen van 't Getf...,De Woonplaats,Thursday,4.0
3193,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2NjA4NTQ4Nz...,596212634,2023-03-23 08:00:03,NaN,Is er genoeg ventilatie en / of kunnen ramen g...,0,0,2023.0,10,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...,Woongoed Zeist,Thursday,3.0
3194,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2NTQwMTMyNz...,100001224379149,2023-03-23 08:00:03,NaN,Sylvana Visser kan je dus straks gebruik van m...,0,0,2023.0,21,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...,Woongoed Zeist,Thursday,3.0
3195,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2MzU0MDgwNz...,100002916564091,2023-03-23 08:00:03,NaN,Komen er nog meer werkplekken bij? Of blijft h...,0,0,2023.0,16,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...,Woongoed Zeist,Thursday,3.0
3196,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIx,ZmVlZGJhY2s6OTYwNDYyMjc0MzY0NTIxXzk2MzUzNzE4ND...,1307930730,2023-03-23 08:00:03,NaN,Goed initiatief.,0,1,2023.0,2,100063452708421,Op de 1e verdieping van het oude schoolgebouw ...,Woongoed Zeist,Thursday,3.0

In [16]:
d1.to_csv(r"C:\Users\20245179\OneDrive - TU Eindhoven\Research Paper\final_data_with_author_names.csv", index=False)